const str = "Hello"
console.log(str)
console.log(str.toUpperCase())
console.log(str.toLocaleLowerCase())
console.log(str.charAt(2))
console.log(str.length)
console.log(str.repeat())
console.log(str.replace('lo','y'))
console.log(str.trim())
console.log(str.includes('u'))
console.log(str.indexOf('H'))
console.log(str.concat(str))
console.log(str.split(''))